version: '3.8'

services:
  app:
    image: aldindockersito30/csv-chat-ai:latest
    container_name: mi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./generated_images:/app/generated_images
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  app-network:
    driver: bridge